<div class="w3-row">
<div class="w3-row l8">
    <div class="w3-col l2">Client</div>
    <div class="w3-col l2">Request title</div>
    <div class="w3-col l2">Review</div>
</div>
<?php

if(sizeof($reviews)>0){
    foreach ($reviews as $review) {?>
    <button class="w3-col l8 accordion">
        <div class="w3-col l2"><?=$review['username']?></div>
        <div class="w3-col l2"><?=$review['title']?></div>
        <div class="w3-col l2">Rated [<?=$review['review']?>/10]</div>
    </button>
        <div class="w3-col l8 panel" style="align-content: center">
        <?php if(strlen($review['review_text'])>0){?>
            <label><?="\"".$review['review_text'] . "\""?></label>
</div>
    <?php } ?>
<?php }} ?>
</div>
