<!-- Table of offers for large -->
<div class="w3-row w3-hide-small">
    <div class="w3-row l8">
        <div id="findWorkTitle" class="w3-col l2">Title</div>
        <div id="findWorkPages" class="w3-col l2">Pages</div>
        <div id="findWorkDifficulty" class="w3-col l2">Difficulty</div>
        <div id="findWorkDeadline" class="w3-col l2">Deadline</div>
    </div>
</div>
<?php
$i = 0;
foreach ($_SESSION['works'] as $work) { ?>
    <button id="correctingClosedBT<?=$work['request_id']?>" class="w3-col l8 accordion">
        <div id="correctingClosedLabelDiv<?=$work['request_id']?>" class="w3-col l3" ><?=$work['title']?></div>
        <div id="correctingClosedLabelDiv<?=$work['request_id']?>" class="w3-col l3" ><?=$work['pages']?></div>
        <div id="correctingClosedLabelDiv<?=$work['request_id']?>" class="w3-col l3" ><?=$work['diff']?></div>
        <div id="correctingClosedLabelDiv<?=$work['request_id']?>" class="w3-col l2" ><?=$work['deadline']?></div>
    </button>
    <div class="w3-col l8 panel" style="align-content: center">
        <form method="POST">
            <div class="w3-col l8"><?=$work['description']?></div>
            <div style="position: relative; bottom: 0;">
                <input class="w3-col l2" type="number" min="0.000" step="0.0001" name="eth<?=$work['request_id']?>">
                <div class="w3-col l1" align="center">ETH</div>
                <input class="w3-col l1 w3-round-large red-border no-border" style="background-color: transparent" type="submit" value="Bind" name="bind<?=$work['request_id']?>">
            </div>
        </form>
    </div>
    <?php $i++; } //}?>
