<form enctype="multipart/form-data" method="POST">
    <div class="w3-row-padding">
            <div>File</div>
            <input id="fulfillDemandFile" class="w3-btn w3-round-large" type="file" name="fileUp" value="Upload">
            <input type="hidden" name="MAX_SIZE" value="8388608" />
            <input class="w3-btn w3-round-large red-border no-border" type="submit" value="Upload">
    </div>
</form>