<form method="post" class="col-md-12">
    <div class="col-md-4">Uživatelské jméno</div>
        <div class="col-md-8">
            <input name="userName" type="text" value="<?php if(isset($_SESSION['userName'])) echo $_SESSION['userName'];?>">
            <?php if (isset($error[0])) {?>
                <span class="glyphicon glyphicon-pencil wrongInput"></span>
                <span><?= $error[0]?></span>
            <?php } ?>
        </div>
    <div class="col-md-4">Heslo</div>
        <div class="col-md-8">
            <input name="passW" type="password" value="<?php if(isset($_SESSION['userName'])) echo $_SESSION['userName'];?>">
            <?php if (isset($error[1])) {?>
                <span class="glyphicon glyphicon-pencil wrongInput"></span>
                <span><?= $error[1]?></span>
            <?php } ?>
        </div>
    <div class="col-md-8 lista" style="margin-top: 1.5em">
        Nejste registrovaní?<a href="?Controler=registration">Registrace</a>
    </div>
        <div class="col-md-4" style="margin-top: 1.5em" align="right">
            <input class="btn" type="submit" value="Přihlásit">
        </div>
</form>