<!DOCTYPE html>
<html>
<title>Red-i <?= $title ?></title>
<?php if (!$GLOBALS['isLocal']) { ?>
    <base href="/~cernyj/">
<?php } ?>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="resources/styles.css">
<link rel="stylesheet" type="text/css" href="resources/w3.css">
<link rel="stylesheet" type="text/css" href="resources/poppins.css">
<link rel="stylesheet" href="resources/bootstrap.icon-large.min.css" >

<!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>-->
<!--<script src="resources/javaScript/designScript.js"></script>-->
<!--<script src="model/meta_mask.js"></script>-->

<style>
    body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
    body {font-size:16px;}
    .w3-half img{margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
    .w3-half img:hover{opacity:1}
</style>
<body>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-red w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
    <a href="?Controler=javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
    <div class="w3-container">
        <h3 class="w3-padding-24"><b>Red - i<br>Correction</b></h3>
    </div>
    <div class="w3-bar-block">
        <a href="?Controller=intro" onclick="w3_close()" id="lololol" class="w3-bar-item w3-button w3-hover-white logo">Home</a>
        <?php if (isset($_SESSION['user_id'])) { ?>
            <a href="?Controller=createDemand" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Create Demand</a>
            <a href="?Controller=findWork" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Find Work</a>
            <a href="?Controller=myOffers" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">My Contracts</a>
        <?php } else { ?>
            <a href="?Controller=login" onclick="loginMM()" class="w3-bar-item w3-button w3-hover-white">Sign in</a>
            <a href="?Controller=registration" class="w3-bar-item w3-button w3-hover-white">Sign up</a>
        <?php } ?>
        <a href="?Controller=howTo" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white" style="bottom: 10px; position: absolute; width: 90%">Q&A</a>
        <div class="w3-hide-large">
            <br>
            <?php if (!isset($_SESSION['user_id'])) {?>
                <a href="?Controller=settings" class="w3-bar-item w3-button w3-hover-white">My Account</a>
            <?php } else { ?>
                <a href="?Controller=login" onclick="loginMM()" class="w3-bar-item w3-button w3-hover-white">Sign in</a>
                <a href="?Controller=registration" class="w3-bar-item w3-button w3-hover-white">Sign up</a>
            <?php }?>
        </div>
    </div>
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-red w3-xlarge w3-padding">
    <a href="?Controler=javascript:void(0)" class="w3-button w3-red w3-margin-right" onclick="w3_open()">☰</a>
    <span>Red-i Correction</span>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<div class="w3-main" style="margin-left:340px;margin-right:40px;margin-top: 30px">
    <!-- Sign in/up large -->
    <div class="w3-hide-small" style="float: right;">
        <?php if (isset($_SESSION['logedin'])) {?>
            <a href="?Controller=settings" class="w3-btn w3-round-large red-border no-border">My Account</a>
        <?php } else { ?>
<!--            <a href="?Controller=login" onclick="post()" class="w3-btn w3-round-large red-border no-border">Sign in</a>-->
            <input type="submit" onclick="loginMM()" class="w3-btn w3-round-large red-border no-border" value="Sign in">
            <a href="?Controller=registration" onclick="set_current_metamask_address()" class="w3-btn w3-round-large red-border no-border">Sign up</a>
<!--            <input type="submit" onclick="post2()" class="w3-btn w3-round-large red-border no-border" value="Sign up">-->
        <?php }?>
    </div>
    <!-- !PAGE CONTENT! -->
    <div class="w3-container " style="margin-top: 20px" id="showcase">
        <h1 class="w3-jumbo"><b><?=$title?></b></h1>
        <h1 class="w3-xxxlarge w3-text-red"><b><?=$subtitle?></b></h1>
        <hr style="width:50px;border:5px solid red" class="w3-round">
    </div>
    <div class="w3-container">
        <?php foreach ($messages as $message) : ?>
            <p class="zprava"><?= $message ?></p>
        <?php endforeach ?>
        <?php $this->controller->buildView(); ?>
    </div>
</div>

<!-- W3.CSS Container -->
<footer class="w3-light-grey w3-container w3-padding-32" style="margin-top:75px;padding-right:58px">
    <div id="metamaskaddress" style="float:right"></div>
    <p class="w3-right" >

        Powered by
        <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">
            w3.css
            <?php
//            echo '<script type="text/javascript">',
//            'get_current_metamask_address();',
//            '</script>';
            ?>
        </a>
    </p>
</footer>
</body>
</html>
<script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="resources/javaScript/designScript.js"></script>
    <script src="model/meta_mask.js"></script>
</script>
