<div class="w3-row">
    <?php if (isset($_SESSION['sentBinds']) || isset($_SESSION['sentOpen']) || isset($_SESSION['sentClosed'])) { ?>
    <h2><b>Sent For Correction</b></h2>
    <?php if (isset($_SESSION['sentBinds'])) { ?>
    <div class="w3-col l12">
    <!-- BINDS -->
    <h2 class="w3-text-red">Binds</h2>
        <div class="w3-row w3-hide-small">
            <div class="w3-row l8">
                <div class="w3-col l2">Title</div>
                <div class="w3-col l2">Deadline</div>
                <div class="w3-col l2">Ethereum</div>
                <div class="w3-col l2">User</div>
            </div>
        </div>
        <?php
        $i = 0;
        foreach ($_SESSION['sentBinds'] as $work) { ?>
            <button class="w3-col l8 accordion">
                <div class="w3-col l3" ><?=$work['label']?></div>
                <div class="w3-col l3" ><?=$work['deadline']?></div>
                <div class="w3-col l3" ><?=$work['eth']?></div>
                <div class="w3-col l2" ><?=$work['user']?></div>
            </button>
            <div class="w3-col l8 panel" style="align-content: center">
                <form method="POST">
                    <input type="submit" value="Reject" name="rejectBind<?=$work['id']?>"
                           class="w3-col l3 w3-round-large red-border no-border" style="float: left; background-color: transparent">
                    <input type="submit" value="Accept" name="acceptBind<?=$work['id']?>"
                           class="w3-col l3 w3-round-large red-border no-border" style="float: right; background-color: transparent">
                </form>
            </div>
            <?php $i++; }?>
    </div>
    <?php } if (isset($_SESSION['sentOpen'])) { ?>
    <div class="w3-col l12">
    <!-- OPEN -->
    <h2 class="w3-text-red">Open</h2>
        <div class="w3-row w3-hide-small">
            <div class="w3-row l8">
                <div class="w3-col l2">Title</div>
                <div class="w3-col l2">Deadline</div>
                <div class="w3-col l2">Ethereum</div>
                <div class="w3-col l2">User</div>
            </div>
        </div>
        <?php
        $i = 0;
        foreach ($_SESSION['sentOpen'] as $work) { ?>
            <button class="w3-col l8 accordion">
                <div class="w3-col l3" ><?=$work['label']?></div>
                <div class="w3-col l3" ><?=$work['deadline']?></div>
                <div class="w3-col l3" ><?=$work['eth']?></div>
                <div class="w3-col l2" ><?=$work['user']?></div>
            </button>
            <div class="w3-col l8 panel" style="align-content: center">
                <form method="POST">
                    <input type="submit" value="Cancel Order" name="cancelOrder<?=$work['id']?>"
                           class="w3-col l3 w3-round-large red-border no-border" style="float: right; background-color: transparent">
                </form>
            </div>
            <?php $i++; }?>
    </div>
    <?php } if (isset($_SESSION['sentClosed'])) { ?>
    <div class="w3-col l12">
    <!-- CLOSED -->
        <h2 class="w3-text-red">Closed</h2>
        <div class="w3-row w3-hide-small">
            <div class="w3-row l8">
                <div class="w3-col l2">Title</div>
                <div class="w3-col l2">Received</div>
                <div class="w3-col l2">Ethereum</div>
                <div class="w3-col l2">User</div>
            </div>
        </div>
        <?php
        $i = 0;
        foreach ($_SESSION['sentClosed'] as $work) { ?>
            <button class="w3-col l8 accordion">
                <div class="w3-col l3" ><?=$work['label']?></div>
                <div class="w3-col l3" ><?=$work['received']?></div>
                <div class="w3-col l3" ><?=$work['eth']?></div>
                <div class="w3-col l2" ><?=$work['user']?></div>
            </button>
            <div class="w3-col l8 panel" style="align-content: center">
                <form method="POST">
                    <input type="submit" value="Download File" name="DownloadFile"
                           class="w3-col l3 w3-round-large red-border no-border" style="float: left; background-color: transparent">
                    <input type="hidden" value="008.png" name="fileDwn">
                    <!-- odstraneno = -neznama chyba(?) a <?//$work['id']?> -neznama chyba(?) z name-->
                </form>
                    <a class="w3-col l3 w3-round-large red-border no-border" style="float: right; background-color: transparent; text-align: center">Send Review</a>
            </div>
        <?php $i++; }?>
        <br>
    </div>
    <?php } ?>
</div>
<?php } if (isset($_SESSION['myBinds']) || isset($_SESSION['correctingOpen']) || isset($_SESSION['correctingClosed'])) { ?>
<br><br>
<div class="w3-col">
    <h2><b>My Corrections</b></h2>
    <?php if (isset($_SESSION['myBinds'])) {?>
    <div class="w3-col l12">
        <!-- My Binds -->
        <h2 class="w3-text-red">Binds</h2>
        <div class="w3-row w3-hide-small">
            <div class="w3-row l8">
                <div class="w3-col l2">Title</div>
                <div class="w3-col l2">Deadline</div>
                <div class="w3-col l2">Ethereum</div>
                <div class="w3-col l2">User</div>
            </div>
        </div>
        <?php
        $i = 0;
        foreach ($_SESSION['myBinds'] as $work) { ?>
            <button class="w3-col l8 accordion">
                <div class="w3-col l3" ><?=$work['label']?></div>
                <div class="w3-col l3" ><?=$work['deadline']?></div>
                <div class="w3-col l3" ><?=$work['eth']?></div>
                <div class="w3-col l2" ><?=$work['user']?></div>
            </button>
            <div class="w3-col l8 panel" style="align-content: center">
                <form method="POST">
                    <input type="submit" value="Cancle" name="cancleBind<?=$work['id']?>"
                           class="w3-col l3 w3-round-large red-border no-border" style="float: right; background-color: transparent">
                </form>
            </div>
            <?php $i++; } }?>
    </div>
    <?php if (isset($_SESSION['correctingOpen'])) {?>
    <div class="w3-col l12">
    <!-- OPEN -->
        <h2 class="w3-text-red">Open</h2>
        <div class="w3-row w3-hide-small">
            <div class="w3-row l8">
                <div class="w3-col l2">Title</div>
                <div class="w3-col l2">Deadline</div>
                <div class="w3-col l2">Ethereum</div>
                <div class="w3-col l2">User</div>
            </div>
        </div>
        <?php
        $i = 0;
        foreach ($_SESSION['correctingOpen'] as $work) { ?>
            <button class="w3-col l8 accordion">
                <div class="w3-col l3" ><?=$work['label']?></div>
                <div class="w3-col l3" ><?=$work['deadline']?></div>
                <div class="w3-col l3" ><?=$work['eth']?></div>
                <div class="w3-col l2" ><?=$work['user']?></div>
            </button>
            <div class="w3-col l8 panel" style="align-content: center">
                <form method="post">
                    <label><input type="submit" value="Upload File" name="UploadFile"
                           class="w3-col l3 w3-round-large red-border no-border" style="float: left; background-color: transparent">
                        File name. <!-- odstraneno = -neznama chyba(?) a <?//$work['id']?> -neznama chyba(?) -->
                    </label>
                    <input type="submit" value="Cancel" name="cancelMyCorrection<?$work['id']?>"
                           class="w3-col l2 w3-round-large red-border no-border" style="float: right; background-color: transparent">
                </form>
            </div>
        <?php $i++; } }?>
        <br>
    </div>
    <?php if(isset($_SESSION['correctingClosed'])) {?>
    <div class="w3-col l12">
    <!-- CLOSED -->
    <h2 class="w3-text-red">Closed</h2>
    <div class="w3-row w3-hide-small">
        <div class="w3-row l8">
            <div class="w3-col l2">Title</div>
            <div class="w3-col l2">Received</div>
            <div class="w3-col l2">Ethereum</div>
            <div class="w3-col l2">User</div>
        </div>
    </div>
    <?php
    $i = 0;
    foreach ($_SESSION['correctingClosed'] as $work) { ?>
        <button class="w3-col l8 accordion">
            <div class="w3-col l3" ><?=$work['label']?></div>
            <div class="w3-col l3" ><?=$work['received']?></div>
            <div class="w3-col l3" ><?=$work['eth']?></div>
            <div class="w3-col l2" ><?=$work['user']?></div>
        </button>
        <div class="w3-col l8 panel" style="text-align: center">
            INSERT REVIEW
        </div>
    <?php $i++; } }?>
    </div>
</div>
<?php } ?>
