<div class="w3-row">
    <?php if (isset($_SESSION['sentRequests']) && sizeof($_SESSION['sentRequests']) > 0
    || isset($_SESSION['sentBinds']) && sizeof($_SESSION['sentBinds']) > 0
    || isset($_SESSION['sentOpen']) && sizeof($_SESSION['sentOpen']) > 0
    || isset($_SESSION['sentClosed']) && sizeof($_SESSION['sentClosed']) > 0) { ?>
    <h2><b>Sent For Correction</b></h2>
    <?php if (isset($_SESSION['sentRequests']) && sizeof($_SESSION['sentRequests'])>0) { ?>
    <div class="w3-col l12">
        <!--     BINDS-->
        <h2 class="w3-text-red">Requests</h2>
        <div class="w3-row w3-hide-small">
            <div class="w3-row l9">
                <div id="titleDiv" class="w3-col l2">Title</div>
                <div id="createdDiv" class="w3-col l2">Created</div>
                <div id="deadlineDiv" class="w3-col l2">Deadline</div>
                <div id="pagesDiv" class="w3-col l1">Pages</div>
                <div id="difficultyDiv" class="w3-col l2">Difficulty</div>
            </div>
        </div>
        <?php
        $i = 0;
        foreach ($_SESSION['sentRequests'] as $work) { //delete request, redirect z uploadu file a uploadu review ?>
            <button class="w3-col l9 accordion">
                <div id="sentRequestsTitle<?=$work['id']?>" class="w3-col l3" ><?=$work['title']?></div>
                <div id="sentRequestsCreated<?=$work['id']?>" class="w3-col l2" ><?=$work['created']?></div>
                <div id="sentRequestsDeadline<?=$work['id']?>" class="w3-col l3" ><?=$work['deadline']?></div>
                <div id="sentRequestsPages<?=$work['id']?>" class="w3-col l2" ><?=$work['pages']?></div>
                <div id="sentRequestsDiff<?=$work['id']?>" class="w3-col l1" ><?=$work['diff']?></div>
            </button>
            <div class="w3-col l9 panel" style="align-content: center">
                <form method="POST">
                    <input type="submit" id="cancelOrderBT<?=$work['request_id']?>" value="Cancel Order" name="cancelOrderSR<?=$work['id']?>"
                           class="w3-col l3 w3-round-large red-border no-border" style="float: right; background-color: transparent">
                </form>
            </div>
        <?php $i++; }?>
    </div>
    <?php } if (isset($_SESSION['sentBinds']) && sizeof($_SESSION['sentBinds'])>0) { ?>
        <div class="w3-col l12">
            <!--     BINDS-->
            <h2 id="bindsH2" class="w3-text-red">Binds</h2>
            <div class="w3-row w3-hide-small">
                <div class="w3-row l8">
                    <div id="titleLabel" class="w3-col l2">Title</div>
                    <div id="deadlineLabel" class="w3-col l2">Deadline</div>
                    <div id="ethereumLabel" class="w3-col l2">Ethereum</div>
                    <div id="userLabel" class="w3-col l2">User</div>
                </div>
            </div>
            <?php
            $i = 0;
            foreach ($_SESSION['sentBinds'] as $work) { ?>
                <button class="w3-col l8 accordion">
                    <div class="w3-col l3" id="sentBindsLabel<?=$work['id']?>"><?=$work['label']?></div>
                    <div class="w3-col l3" id="sentBindsDeadline<?=$work['id']?>" ><?=$work['deadline']?></div>
                    <div class="w3-col l3" id="sentBindsEth<?=$work['id']?>" ><?=$work['eth']?></div>
                    <div class="w3-col l2" id="sentBindsUser<?=$work['id']?>" ><?=$work['user']?></div>
                </button>
                <div class="w3-col l8 panel" style="align-content: center">
                    <form method="POST">
                        <input type="submit" value="Reject" id="rejectBindBT<?=$work['id']?>" name="rejectBind<?=$work['id']?>"
                               class="w3-col l3 w3-round-large red-border no-border" style="float: left; background-color: transparent">
                    </form>
                        <button id="acceptBindBT<?=$work['id']?>" onclick="prepare_and_deploy(<?=$work['id']?>,<?=$work['req_id']?>)" name="acceptBind<?=$work['id']?>"
                                class="w3-col l3 w3-round-large red-border no-border" style="float: right; background-color: transparent">Accept</button>
                </div>
                <?php $i++; }?>
        </div>
    <?php } if (isset($_SESSION['sentOpen']) && sizeof($_SESSION['sentOpen'])>0) { ?>
        <div class="w3-col l12">
            <!--     OPEN-->
            <h2 id="openLabel" class="w3-text-red">Open</h2>
            <div class="w3-row w3-hide-small">
                <div class="w3-row l8">
                    <div id="titleLabel2" class="w3-col l2">Title</div>
                    <div id="deadlineLabel2" class="w3-col l2">Deadline</div>
                    <div id="ethereumLabel2" class="w3-col l2">Ethereum</div>
                    <div id="userLabel2" class="w3-col l2">User</div>
                </div>
            </div>
            <?php
            $i = 0;
            foreach ($_SESSION['sentOpen'] as $work) { ?>
                <button class="w3-col l8 accordion">
                    <div id="sentOpenLanel<?=$work['id']?>"  class="w3-col l3" ><?=$work['label']?></div>
                    <div id="sentOpenDeadline<?=$work['id']?>" class="w3-col l3" ><?=$work['deadline']?></div>
                    <div id="sentOpenEth<?=$work['id']?>" class="w3-col l3" ><?=$work['eth']?></div>
                    <div id="sentOpenUser<?=$work['id']?>" class="w3-col l2" ><?=$work['user']?></div>
                </button>
                <div class="w3-col l8 panel" style="align-content: center">
                    <?php
                    $add = $work['address'];
                    if (strlen($add) == 0)
                        $add = "-1";
                    if ($work['state']==2){?>
<!--                        <form method="POST">-->
                        <button id="cancelOrder2BT<?=$work['id']?>" onclick="call_customer_cancel(<?=$add?>, <?=$work['id']?>)"
                                class="w3-col l3 w3-round-large red-border no-border" style="float: right; background-color: transparent">Cancel Order</button>
<!--                        </form>-->
                    <?php } else { ?>
                        <label>File already downloaded by corrector - can't be canceled.</label>
                    <?php } ?>
                </div>
                <?php $i++; } ?>
        </div>
    <?php }
    if (isset($_SESSION['sentClosed']) && sizeof($_SESSION['sentClosed'])>0) { ?>
        <div class="w3-col l12">
            <!--     CLOSED-->
            <h2 class="w3-text-red">Closed</h2>
            <div class="w3-row w3-hide-small">
                <div class="w3-row l8">
                    <div id="closedTitleBT" class="w3-col l2">Title</div>
                    <div id="closedReceivedBT" class="w3-col l2">Received</div>
                    <div id="closedEthereumBT" class="w3-col l2">Ethereum</div>
                    <div id="closedUserBT" class="w3-col l2">User</div>
                </div>
            </div>
            <?php
            $i = 0;
            foreach ($_SESSION['sentClosed'] as $work) { ?>
                <button class="w3-col l8 accordion">
                    <div id="sentClosedLabel<?=$work['label']?>" class="w3-col l3" ><?=$work['label']?></div>
                    <div id="sentClosedReceived<?=$work['received']?>" class="w3-col l3" ><?=$work['received']?></div>
                    <div id="sentClosedEth<?=$work['eth']?>" class="w3-col l3" ><?=$work['eth']?></div>
                    <div id="sentClosedUser<?=$work['user']?>" class="w3-col l2" ><?=$work['user']?></div>
                </button>
                <div class="w3-col l8 panel" style="align-content: center">
                    <form method="POST">
                        <?php if($work['review']<0){?>
                            <input id="sendReviewBT<?=$work['id']?>" type="submit" value="Send Review" name="SendReview<?=$work['id']?>"
                                   class="w3-col l3 w3-round-large red-border no-border" style="float: left; background-color: transparent">
                        <?php } else {?>
                            <label id="reviewLabel<?=$work['id']?>" style="float: left">You rated [<?=$work['review']?>/10]</label>
                        <?php } ?>
                        <input id="downloadFileBT<?=$work['id']?>" type="submit" value="Download File" name="DownloadCorrected<?=$work['id']?>"
                               class="w3-col l3 w3-round-large red-border no-border" style="float: right; background-color: transparent">
                        <?php if(strlen($work['review_text'])>0 && $work['review_text']!="No additional text"){?> <br>
                            <label id="reviewTextLabel<?=$work['id']?>"><?="\"".$work['review_text'] . "\""?></label>
                        <?php } ?>
                    </form>
                </div>
                <?php $i++; }?>
            <br>
        </div>
    <?php } ?>
</div>
<?php } if (isset($_SESSION['correctingBinds']) && sizeof($_SESSION['correctingBinds'])>0
            || isset($_SESSION['correctingOpen']) && sizeof($_SESSION['correctingOpen'])>0
            || isset($_SESSION['correctingClosed']) && sizeof($_SESSION['correctingClosed'])>0) { ?>
    <br><br>
    <div class="w3-col">
        <h2><b>My Corrections</b></h2>
        <?php if (isset($_SESSION['correctingBinds']) && sizeof($_SESSION['correctingBinds'])>0) {?>
        <div class="w3-col l12">
            <!--         My Binds-->
            <h2 class="w3-text-red">Binds</h2>
            <div class="w3-row w3-hide-small">
                <div class="w3-row l8">
                    <div id="bindsTitleDiv" class="w3-col l2">Title</div>
                    <div id="bindsDeadlineDiv" class="w3-col l2">Deadline</div>
                    <div id="bindsEthereumDiv" class="w3-col l2">Ethereum</div>
                    <div id="bindsUserDiv" class="w3-col l2">User</div>
                </div>
            </div>
            <?php
            $i = 0;
            foreach ($_SESSION['correctingBinds'] as $work) { ?>
                <button class="w3-col l8 accordion">
                    <div id="correctingBindsLabel<?=$work['label']?>" class="w3-col l3" ><?=$work['label']?></div>
                    <div id="correctingBindsDeadline<?=$work['deadline']?>" class="w3-col l3" ><?=$work['deadline']?></div>
                    <div id="correctingBindsEth<?=$work['eth']?>" class="w3-col l3" ><?=$work['eth']?></div>
                    <div id="correctingBindsUser<?=$work['user']?>" class="w3-col l2" ><?=$work['user']?></div>
                </button>
                <div class="w3-col l8 panel" style="align-content: center">
                    <form method="POST">
                        <input id="cancelBindBT<?=$work['id']?>" type="submit" value="Cancel" name="cancelBind<?=$work['id']?>"
                               class="w3-col l3 w3-round-large red-border no-border" style="float: right; background-color: transparent">
                    </form>
                </div>
                <?php $i++; } }?>
        </div>
        <?php if (isset($_SESSION['correctingOpen']) && sizeof($_SESSION['correctingOpen'])>0) {?>
        <div class="w3-col l12">
            <!--     OPEN-->
            <h2 id="OpenH2" class="w3-text-red">Open</h2>
            <div class="w3-row w3-hide-small">
                <div class="w3-row l8">
                    <div id="OpenTitleDiv" class="w3-col l2">Title</div>
                    <div id="OpenDeadlineDiv" class="w3-col l2">Deadline</div>
                    <div id="OpenEthereumDiv" class="w3-col l2">Ethereum</div>
                    <div id="OpenUserDiv" class="w3-col l2">User</div>
                </div>
            </div>
            <?php
            $i = 0;
            foreach ($_SESSION['correctingOpen'] as $work) { ?>
                <button class="w3-col l8 accordion">
                    <div id="correctingOpenLabel<?=$work['id']?>" class="w3-col l3" ><?=$work['label']?></div>
                    <div id="correctingOpenDeadline<?=$work['id']?>" class="w3-col l3" ><?=$work['deadline']?></div>
                    <div id="correctingOpenEth<?=$work['id']?>" class="w3-col l3" ><?=$work['eth']?></div>
                    <div id="correctingOpenUser<?=$work['id']?>" class="w3-col l2" ><?=$work['user']?></div>
                </button>
                <div class="w3-col l8 panel" style="align-content: center">
                    <form enctype="multipart/form-data" method="post">
                        <?php if($work['state']==2) {?>
                        <input id="downloadFileToCorrectBT<?=$work['id']?>" type="submit" value="Download File"
                               name="downloadToCorrect<?=$work['id']?>"
                               class="w3-col l3 w3-round-large red-border no-border" style="float: left; background-color: transparent">
                            <button id="cancelMyCorrectionBT<?=$work['id']?>" onclick="call_corrector_cancel(<?=$work['address']?>, <?=$work['id']?>)"
                                    class="w3-col l2 w3-round-large red-border no-border" style="float: right; background-color: transparent">Cancel</button>
                    </form>
                        <?php } elseif ($work['state']==3) { ?>
                            <div class="w3-row l8" style="float: left">
<!--                                <input class="w3-btn w3-col l7 w3-round-large" type="file" name="fileUp--><?//=$work['id']?><!--" value="Upload">-->
                                <input class="w3-btn w3-col l7 w3-round-large" type="file" name="fileUp<?=$work['id']?>" value="Upload">
                                <input type="submit" value="Upload" name="UploadFile<?=$work['id']?>"
                                       class="w3-col l2 w3-round-large red-border no-border" style="background-color: transparent">
                    </form>
                            </div>
                            <?php if ($work['uploaded_id'] != $work['file_id']) { ?>
                    </form>
                                <button onclick="call_corrector_done(<?=$work['address']?>)" class="w3-col l2 w3-round-large red-border no-border"
                                        style="float: right; background: transparent">Confirm</button>
                        <?php } } ?>

                </div>
                <?php $i++; } }?>
            <br>
        </div>
        <?php if(isset($_SESSION['correctingClosed']) && sizeof($_SESSION['correctingClosed'])>0) {?>
        <div class="w3-col l12">
            <!--     CLOSED-->
            <h2 id="closedH22" class="w3-text-red">Closed</h2>
            <div class="w3-row w3-hide-small">
                <div class="w3-row l8">
                    <div id="closedTitleDiv" class="w3-col l2">Title</div>
                    <div id="closedReceivedDiv" class="w3-col l2">Received</div>
                    <div id="closedEthereumDiv" class="w3-col l2">Ethereum</div>
                    <div id="closedUserDiv" class="w3-col l2">User</div>
                </div>
            </div>
            <?php
            $i = 0;
            foreach ($_SESSION['correctingClosed'] as $work) { ?>
                <button class="w3-col l8 accordion">
                    <div id="correctingClosedLabelDiv<?=$work['label']?>" class="w3-col l3" ><?=$work['label']?></div>
                    <div id="correctingClosedReceivedDiv<?=$work['received']?>" class="w3-col l3" ><?=$work['received']?></div>
                    <div id="correctingClosedEthDiv<?=$work['eth']?>" class="w3-col l3" ><?=$work['eth']?></div>
                    <div id="correctingClosedUserDiv<?=$work['user']?>" class="w3-col l2" ><?=$work['user']?></div>
                </button>
                <?php if($work['review'] > 0){?>
                <div class="w3-col l8 panel" style="text-align: left">
                    <label id="correctingClosedReviewLabel<?=$work['review']?>">Your rating: [<?=$work['review'] ."/10"?>]</label>
                    <?php if(strlen($work['review_text'])>0 && $work['review_text']!="No additional text") {?> <br>
                        <label id="correctingClosedReviewTextLabel<?=$work['review']?>"><?="\"".$work['review_text']."\""?></label>
                    <?php } ?>
                </div>
                <?php } else { ?>
                    <div class="w3-col l8 panel" style="text-align: left">
                        <label>Your rating: Waiting for client's review</label>
                <?php } $i++; } }?>
        </div>
    </div>
<?php } ?>
