<form method="post" class="col-md-12">
    <div class="col-md-4">Username</div>
        <div class="col-md-8">
            <input name="userName" type="text"
                     value="<?php if(isset($_SESSION['regUsername'])) echo $_SESSION['regUsername'];?>">
            <?php if (isset($error[0])) {?>
                <span class="glyphicon glyphicon-pencil wrongInput"></span>
                <span><?=$error[0]?></span>
            <?php } ?>
<!--            <input type="submit" value="">-->
        </div>
    <div class="col-md-4" style="padding-top: 0.5em">Email</div>
    <div class="col-md-8">
        <input name="mail" type="text" value="<?php if(isset($_SESSION['mail'])) echo $_SESSION['mail'];?>">
        <?php if (isset($error[1])) {?>
            <span class="glyphicon glyphicon-pencil wrongInput"></span>
            <span><?=$error[1]?></span>
        <?php } ?>
    </div>
    <div class="col-md-4" style="padding-top: 0.5em">MetaMask Address</div>
        <div class="col-md-8">
            <input id="metamaskReg" name="metamask" type="text" value="undefined" readonly="readonly">
            <div id="mmErr" style="visibility: hidden">
                <label style="color: red">You need to be logged in to your MetaMask account to be registered.</label>
                <a href="?Controller=howTo">Learn more!</a>
            </div>
        </div>
    <div class="col-md-12" style="margin-top: 1.5em">
        <div class="col-md-9" style="font-size: small;">
            After successful registration you'll be automatically logged in and redirected to homepage.
        </div>
        <div class="col-md-3" align="right">
            <input class="w3-btn w3-round-large red-border no-border" name="regSubmit" type="submit" value="Sign up">
        </div>
    </div>
</form>

<script>
    window.onload = function () {
        setTimeout(post2, 50);
    }
</script>