<div class="w3-row">
    <form method="POST">
        <div class="w3-col l12">
            Review
        </div>
        <div class="w3-col l12">
            <textarea rows="12" cols="50" maxlength="400" style="resize: none" name="review"></textarea>
        </div>
        <div class="w3-col l4">
            <label>
                <input type="number" min="1" max="10" step="1" name="stars">
            </label>
            Stars
        </div>
        <div class="w3-col l4">
            <input type="submit" value="Send" name="submitReview" class="w3-col l4 w3-round-large red-border no-border" style="background-color: transparent">
        </div>
    </form>
</div>