<h2>Settings</h2>
<form type="POST">
    <div>
        <label>
            <input type="checkbox" name="corrector">
            I want to be listed as a corrector
        </label>
    </div>
    <div class="w3-row">
        <div class="w3-col l8" style="float: right">
            <input type="submit" value="Save" name="save" class="w3-btn w3-round-large red-border no-border">
        </div>
    </div>
</form>
<a href="accountReviews">My Reviews</a>